networks:
  expense:

volumes:
  mysql: #docker volume create mysql
        
services:
  # docker run -d --name mongodb --network=roboshop mongodb:1

  backend:
    image: rajesh028/backend:v1.0
    container_name: backend
    depends_on:
      - mysql
    networks:
      - expense
    

  frontend:
    image: rajesh028/frontend:v1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
    - "80:80"#
    networks:
      - expense
    

  mysql:
    image: rajesh028/mysql:v1.0
    container_name: mysql
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume
    networks:
      - expense
  



      